#!/usr/bin/env zsh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xff81a1c1
# yabai -m config active_window_border_color   0xffDCEDC1
yabai -m config normal_window_border_color   0xff505050
# yabai -m config insert_window_border_color   0xffd75f5f
# yabai -m config insert_feedback_color        0xaa7c5c9c
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# Rules
# yabai -m rule --add label=whatsapp app="^WhatsApp$" space=11
# yabai -m rule --add label=slack app="^Slack$" space=10
yabai -m rule --add app=Stats manage=off
# yabai -m rule --add app=Music manage=off
# yabai -m rule --add app=Emacs manage=on

function record_display_id {
  display_id=$(yabai -m query --windows --window | jq '.display')
  ruby $HOME/display_focus.rb write $display_id
}

function focus_current_display {
  yabai -m display --focus $(ruby $HOME/display_focus.rb read)
}

# yabai -m signal --add event=window_focused action="${functions[record_display_id]}"
# yabai -m signal --add event=application_front_switched action="${functions[record_display_id]}"
# yabai -m signal --add event=window_destroyed action="${functions[focus_current_display]}"
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null" 
yabai -m signal --add event=application_terminated action="${functions[focus_current_display]}"

echo "yabai configuration loaded.."
